dist: bionic
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      env: CONFIGURATION=Debug USE_CPP11=1
    - os: linux
      env: CONFIGURATION=Debug USE_CPP11=0
    - os: linux
      env: CONFIGURATION=Release USE_CPP11=1
    - os: linux
      env: CONFIGURATION=Release USE_CPP11=0
    - os: osx
      osx_image: xcode10.2
      env: CONFIGURATION=Debug USE_CPP11=1
    - os: osx
      osx_image: xcode10.2
      env: CONFIGURATION=Debug USE_CPP11=0
    - os: osx
      osx_image: xcode10.2
      env: CONFIGURATION=Release USE_CPP11=1
    - os: osx
      osx_image: xcode10.2
      env: CONFIGURATION=Release USE_CPP11=0

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION -DUSE_CPP11=$USE_CPP11 ..
    - make -j4
    - ctest --verbose

notifications:
  email:
    on_success: change
    on_failure: change
