sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get install -y valgrind; fi

script:
    - $CXX --version
    - ./test.sh Debug
    - ./test.sh Release

notifications:
  email:
    on_success: change
    on_failure: change
