dist: trusty
sudo: false
language: cpp

os:
    - linux
    - osx
  
compiler:
    - gcc
    - clang

script:
    - cd src
    - $CXX --version
    - ./compile_test.sh debug
    - ./test.debug --use-colour no --order rand --rng-seed 'time' 
    - ./compile_test.sh release
    - ./test.release --use-colour no --order rand --rng-seed 'time'

notifications:
  email:
    on_success: change
    on_failure: change
