dist: bionic
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      env: CONFIGURATION=Debug
    - os: linux
      env: CONFIGURATION=Release
    - os: osx
      osx_image: xcode10.2
      env: CONFIGURATION=Debug
    - os: osx
      osx_image: xcode10.2
      env: CONFIGURATION=Release

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ..
    - make -j4
    - ctest --verbose

notifications:
  email:
    on_success: change
    on_failure: change
