sudo: false
language: cpp

branches:
  only:
    - master
    - master_cpp11

matrix:
  include:
    - os: linux
      env: CONFIGURATION=Debug
      compiler: gcc
    - os: linux
      env: CONFIGURATION=Debug
      compiler: clang
    - os: osx
      env: CONFIGURATION=Debug
      compiler: clang
    - os: linux
      env: CONFIGURATION=Release
      compiler: gcc
    - os: linux
      env: CONFIGURATION=Release
      compiler: clang
    - os: osx
      env: CONFIGURATION=Release
      compiler: clang

script:
    - mkdir build && cd build
    - CPPSTD="-std=c++17"
    - if [ "$TRAVIS_BRANCH" = "master_cpp11" ]; then CPPSTD="-std=c++11"; fi
    - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION -DCMAKE_CXX_COMPILER_ARG1=$CPPSTD ..
    - make -j4
    - ctest --verbose

notifications:
  email:
    on_success: change
    on_failure: change
