sudo: required
language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7
        - CONFIGURATION=Debug
    - os: linux
      compiler: g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7
        - CONFIGURATION=Release
    - os: osx
      osx_image: xcode10 
      compiler: clang++
      env: CONFIGURATION=Debug
    - os: osx
      osx_image: xcode10 
      compiler: clang++
      env: CONFIGURATION=Release

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ..
    - make -j4
    - ctest --verbose

notifications:
  email:
    on_success: change
    on_failure: change
