sudo: required
language: cpp

branches:
  only:
    - master

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CONFIGURATION=Debug
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CONFIGURATION=Release

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ..
    - make -j4
    - ctest --verbose

notifications:
  email:
    on_success: change
    on_failure: change
